import DataLinejhf12resource_characteristic_logEController from '../data-line-jhf12-resource-characteristic-log-e';

var DataLinejhf12resource_characteristic_logENewController = DataLinejhf12resource_characteristic_logEController;
export default DataLinejhf12resource_characteristic_logENewController;
