import DataLinejhf12characteristic_typeEController from '../data-line-jhf12-characteristic-type-e';

var DataLinejhf12characteristic_typeENewController = DataLinejhf12characteristic_typeEController;
export default DataLinejhf12characteristic_typeENewController;
